function transition1
    close all;
    clear all;

    appName = '你好啊'
    screenSize = get(0,'ScreenSize');
    mainWindow = figure('Name', appName,...
                'NumberTitle','Off',...
                'Menubar','none',...
                'Resize','off',...
                'color',[0 0 0],...
                'Units','pixels',...
                'Position',[0.5*(screenSize(3)-800),...
                            0.5*(screenSize(4)-600),...
                            800,650],...
                'DeleteFcn',@closeWindowFn);
            
%     title = uicontrol('Parent',mainWindow,...
%                     'Style','text',...
%                     'String' ,appName,...
%                     'FontSize',48,...
%                     'FontName','你好阿大哥哥',...
%                     'FontWeight','bold',...
%                     'BackgroundColor',[0 0 0],...
%                     'ForegroundColor',[1,1,1],...
%                     'HorizontalAlignment','center',...
%                     'Units','pixels',...
%                     'Position',[175,398,500,70]);
            
    startBtn = uicontrol('Parent',mainWindow,...
              'Style','pushbutton',...
              'String','來吧，康妮',...
              'FontSize',18,...
              'FontWeight','bold',...
              'FontName','微軟正黑體',...
              'Units','pixels',...
              'Position',[100,25,300,45],...
              'Callback',@startGameFn);

    closeBtn = uicontrol('Parent',mainWindow,...
              'Style','pushbutton',...
              'String','先撤退好了...',...
              'FontSize',14,...
              'FontWeight','bold',...
              'FontName','微軟正黑體',...
              'Units','pixels',...
              'Position',[410,25,300,45],...
              'Callback',@closeWindowFn);
    
%     gifPlayerGUI("main.gif");
%    img = uicontrol('Parent', mainWindow,...
%        

    imshow("second.jfif");
    function gifPlayerGUI(fname)
        %# read all GIF frames
        info = imfinfo(fname, 'gif');
        delay = ( info(1).DelayTime ) / 100;
        [img,map] = imread(fname, 'gif', 'frames','all');
        [imgH,imgW,~,numFrames] = size(img);
        movegui(mainWindow,'center')
        hAx = axes('Parent',mainWindow, ...
            'Units','pixels', 'Position',[0 0 1180 680]);
        hImg = imshow(img(:,:,:,1), map, 'Parent',hAx);
        pause(delay)

        %# loop over frames continuously
        counter = 1;
        while ishandle(hImg)
            %# increment counter circularly
            counter = rem(counter, numFrames) + 1;

            %# update frame
            set(hImg, 'CData',img(:,:,:,counter))

            %# pause for the specified delay
            pause(delay)
        end
    end
          
    function startGameFn(~, ~)
        example
    end
    
    function closeWindowFn(~, ~)
        delete(mainWindow)
    end
end